# TODO: verify functions, dplyr is a mess in packaged functions
# implict referential behaviour etc.

#' Add eurostat population numbers to CEIP data frame. Warning: only available from 2007!
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' @return Merges the two databases
#' @keywords emission, voc, population
#' @export

ceip_add_population <- function(df) {

  # check if the data class is correct
  if(!any(class(df) == "ceipr_data")){
    stop("Data is not of class ceipr_data, not valid ceipr data!")
  }

  # Load the data set for EU population data
  EU_population_data <- eurostat::get_eurostat("tps00001") %>%
    # convert the timestamp to a year, for better referencing
    dplyr::mutate(year=strtoi(format(time,'%Y')),geo=as.character(geo)) %>%
    # rename some variables to make things easier
    dplyr::rename(population = values,eurostat=geo,eurostat_year=year) %>%
    # add country names and EU status
    dplyr::left_join(countrycode::codelist_panel,by="eurostat") %>%
    # narrow the results down
    dplyr::select(iso2 = iso2c,country=country.name.en,population,eu28,year=eurostat_year)

  return(
    dplyr::right_join(df, EU_population_data, by = c("iso2","year"))
  )
}

#' Calculate per capita emissions
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' and supplemented with eurostat data using ceip_add_population()
#' @return Merges the two databases
#' @keywords emission, voc, population
#' @export

ceip_population_emissions <- function(df) {

  # check if the data class is correct
  if(!any(class(df) == "ceipr_data")){
    stop("Data is not of class ceipr_data, not valid ceipr data!")
  }

  # check if the eurostat data is included
  if(!any(grepl("population", names(df)))){
    stop("No population data found in the ceipr data frame.
         Use the ceip_add_population() function to merge in eurostat data.")
  }

  # calculate the emissions per capita
  ceipr$population_emission <- with(df, emission/population)
}
