#' Run a simple linear regression on the
#' the Centre on Emission Inventories and Projections (CEIP)
#' emission data as formatted using ceip_download()
#'
#' @param file path to a file generated by ceip_download()
#' @param out_dir output directory
#' @param internal logical TRUE / FALSE
#' @return geotiff written to disk
#' @keywords emission, voc
#' @export
#' @examples
#'
#' \dontrun{
#' ceip_download()
#'}

ceip_regression <- function(file = "~/SOx_A.tif",
                            out_dir = "~",
                            plot = FALSE){

  # load required libraries
  library(raster)
  
  # read in the data
  s <- brick(file)
  
  # regression of values in one brick (or stack) with 'time'
  time <- 1:nlayers(s)
  
  # define different values to extract
  # sadly can't be done in one pass
  # calc only allows you to return one value
  slope_fun <- function(x) {
    if(all(is.na(x))){
      NA
    } else {
      lm(x ~ time)$coefficients[2]
    }
  }
  
  r2_fun <- function(x) {
    if(all(is.na(x))){
      NA
    } else {
      fit <- lm(x ~ time)
      summary(fit)$r.squared
    }
  }
  
  # calculate statistics
  slope <- raster::calc(s, slope_fun)
  r_squared <-raster::calc(s, r2_fun)
  
  # combine data, assign layer names
  fit_data <- raster::stack(slope, r_squared)
  names(fit_data) <- c("slope","r_squared")
  
  # return a raster stack with regression
  # parameters
  return(fit_data)
}
