#' Run a simple linear regression on the
#' the Centre on Emission Inventories and Projections (CEIP)
#' emission data as formatted using ceip_download()
#'
#' @param file path to a file generated by ceip_download()
#' @param out_dir output directory
#' @param internal logical TRUE / FALSE
#' @return geotiff written to disk
#' @keywords emission, voc
#' @export
#' @examples
#'
#' \dontrun{
#' ceip_download()
#'}

ceip_regression <- function(file = "~/SOx_A.tif",
                            out_dir = "~",
                            internal = TRUE){
  # read in the data
  s <- raster::brick(file)

  # for statistical consistency set seed
  set.seed(0)

  # regression of values in one brick (or stack) with 'time'
  time <- 1:raster::nlayers(s)

  # define different values to extract
  # sadly can't be done in one pass
  # calc only allows you to return one value
  slope_fun <- function(x) {
    if(all(is.na(x))){
      NA
    } else {
      stats::lm(x ~ time)$coefficients[2]
    }
  }

  r2_fun <- function(x) {
    if(all(is.na(x))){
      NA
    } else {
      fit <- stats::lm(x ~ time)
      summary(fit)$r.squared
    }
  }

  p_fun <- function(x) {
    if(all(is.na(x))){
      NA
    } else {
      fit <- stats::lm(x ~ time)
      summary(fit)$coefficients[2,4]
    }
  }

  # calculate statistics
  slope <- raster::calc(s, slope_fun)
  r_squared <-raster::calc(s, r2_fun)
  p_value <-raster::calc(s, p_fun)

  # combine data, assign layer names
  fit_data <- raster::stack(slope, r_squared, p_value)
  names(fit_data) <- c("slope","r_squared", "p_value")

  # return a raster stack with regression
  # parameters
  if(internal){
    return(fit_data)
  } else {
    raster::writeRaster(fit_data,
                        paste0(tools::file_path_sans_ext(file),"_regression.tif"),
                        overwrite = TRUE,
                        options = "COMPRESS=DEFLATE")
    }
}
