#' Plot Centre on Emission Inventories and Projections (CEIP)
#' emission regression data as formatted using ceip_regression()
#'
#' @param file path to a file generated by ceip_regression()
#' @param out_dir output directory
#' @param internal logical TRUE / FALSE
#' @return geotiff written to disk
#' @keywords emission, voc
#' @export
#' @examples
#'
#' \dontrun{
#' ceip_plot_regression()
#'}
