#' Converts text based data from the
#' Centre on Emission Inventories and Projections (CEIP)
#' into raster grid data (geotiff or raster object in the R workspace)
#'
#' @param df CEIP data frame generated by ceip_read()
#' @param year which years to cover (default = 2000:2016)
#' @param pollutant emission values to include (default = "NOx")
#' @param sector sector to visualize
#' @param country country to visualize, if NULL all (default = \code{NULL})
#' @param out_dir directory where to store the geotiff if written to file
#' (default = tempdir())
#' @param trim shrink map to the area covered by data (default = \code{TRUE})
#' @param internal bolean \code{TRUE} / \code{FALSE}, write output to disk or
#' return raster stack to R workspace
#' @return Returns a geotiff written to disk or raster stack returned
#' to the R workspace when written to disk the out_dir location is used.
#' @keywords emission, voc
#' @export
#' @examples
#'
#' \dontrun{
#' ceip_grid()
#'}
#' @importFrom magrittr %>%

ceip_to_raster <- function(df,
                      year = 2000:2016,
                      pollutant = "SOx",
                      sector = "A",
                      country = NULL,
                      out_dir = tempdir(),
                      trim = TRUE,
                      internal = TRUE){

  # sanity checks
  if(nrow(df) == 0 | is.null(df)){
    stop("Data file is empty, check df parameter!")
  }

  # convert the data from a dataframe to a raster
  # for a subset of the data
  rasters <- year %>% map(function(y)
      filter(df,
             if (!is.null(country)) {
               iso2 == !!country &
                 year == !!y &
                 pollutant == !!pollutant &
                 sector_abbr == !!sector
             } else {
               year == !!y &
                 pollutant == !!pollutant &
                 sector_abbr == !!sector
             }) %>%
        ceipr::convert_to_raster())

  # combine all data into a stack
  rasters <- raster::stack(rasters)

  # trim the raster (shrink to area covered)
  # if required
  if (trim){
    rasters <- raster::trim(rasters)
  }

  # if internal return the raster stack
  # otherwise write to file
  if(internal){
    return(rasters)
  } else {
    raster::writeRaster(rasters,
                        paste0(out_dir,'/',pollutant,'_',sector,'.tif'),
                        overwrite = TRUE)
  }
}
