# TODO: verify functions, ggplot is a mess in packaged functions

#' Visualize CEIP trends in emissions
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' @param group group to sort by (default = "iso2")
#' @param group_label group label to use (default = "country")
#' @param subject subject line (default = "")
#' @param title plot title
#' @return ggplot object to be plotted
#' @keywords emission, voc, plot, trend
#' @export
ceip_trends <- function(df,
                        group = "iso2",
                        group_label = "country",
                        subject = "",
                        title = paste(subject,"trends per",
                                      group_label,sep = " ")){
  if(!all(c("total_emissions","year") %in% names(df))) {
    stop("Data must contain an total_emissions and year variable.")
  }

  unit <- df[1,]$unit

  ggplot2::ggplot(df) +
    ggplot2::geom_line(mapping= ggplot2::aes_string(x="year",y="total_emissions",color=group)) +
    ggplot2::labs(
      title = title,
      x = "Year",
      y = glue::glue("Emissions ({unit})"),
      color = group_label)
}

#' Compare CEIP total emissions
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' @param group group to sort by (default = "iso2")
#' @param group_label group label to use (default = "country")
#' @param subject subject line (default = "")
#' @param title plot title
#' @param rank rank bars from high to low (default = FALSE)
#' @return ggplot object to be plotted
#' @keywords emission, voc, plot, trend
#' @export
ceip_compare_totals <- function(df,
                             group = "iso2",
                             group_label = "country",
                             subject = "",
                             title = paste(subject, "comparison per",
                                           group_label, sep = " "),
                             rank = FALSE){
  if(!all(c("total_emissions") %in% names(df))) {
    stop("Data must contain an total_emissions variable. Did you run ceip_totals?")
  }
  unit <- df[1,]$unit
  bar_plot(df,group = group,group_label = group_label,title = title,unit=unit,rank=rank)
}

#' Compare CEIP emissions per person
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' @param group group to sort by (default = "iso2")
#' @param group_label group label to use (default = "country")
#' @param subject subject line (default = "")
#' @param title plot title
#' @param rank rank bars from high to low (default = FALSE)
#' @return ggplot object to be plotted
#' @keywords emission, voc, plot, trend
#' @export
ceip_compare_pp <- function(df,
                                group = "iso2",
                                group_label = "country",
                                subject = "",
                                title = paste(subject, "comparison emissions per person per",
                                              group_label, sep = " "),
                                rank=FALSE){
  if(!all(c("emissions_pp","unit_pp") %in% names(df))) {
    stop("Data must contain an emissions_pp and unit_pp variable. Did you run ceip_population_emissions?")
  }
  unit <- df[1,]$unit_pp
  bar_plot(df,group = group,group_label = group_label,y="emissions_pp",title = title,unit=unit,rank=rank)
}


#' Internal function
bar_plot <- function(df,group,group_label,y="total_emissions",title,unit,rank=FALSE) {
  if (rank) {
    x <- glue::glue("reorder({group},-{y})")
  } else {
    x <- group
  }
  ggplot2::ggplot(df) +
    ggplot2::geom_bar(
      mapping =  ggplot2::aes_string(x = x, y = y, fill = group),
      stat = "identity",
      position = "dodge"
    ) +
    ggplot2::labs(
      title = title,
      x = group,
      y = glue::glue("Emissions ({unit})"),
      color = group_label
    )
}
