# TODO: verify functions, ggplot is a mess in packaged functions

#' Visualize CEIP trends in emissions
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' @param group group to sort by (default = "iso2")
#' @param group_label group label to use (default = "country")
#' @param subject subject line (default = "")
#' @param title plot title
#' @return ggplot object to be plotted
#' @keywords emission, voc, plot, trend
#' @export
ceip_trends <- function(df,
                        group = "iso2",
                        group_label = "country",
                        subject = "",
                        title = paste(subject,"trends per",
                                      group_label,sep = " ")){
  if(!any(class(df) == "ceipr_totals")){
    stop("Data is not of class ceipr_totals, did you use ceip_totals to convert to totals?")
  }
  ggplot2::ggplot(pollution_totals) +
    ggplot2::geom_line(mapping= ggplot2::aes_string(x="year",y="total_emissions",color=group)) +
    ggplot2::labs(
      title = title,
      x = "Year",
      y = "Emissions (ton)",
      color = group_label)
}

#' Compare CEIP emissions between years
#'
#' @param df CEIP data frame generated by ceip_read() (of class ceipr_data)
#' @param year year to evaluate (default = 2000)
#' @param group group to sort by (default = "iso2")
#' @param group_label group label to use (default = "country")
#' @param subject subject line (default = "")
#' @param title plot title
#' @return ggplot object to be plotted
#' @keywords emission, voc, plot, trend
#' @export
ceip_comparisons <- function(df,
                             group = "iso2",
                             year = 2000,
                             group_label = "country",
                             subject = "",
                             title = paste(subject, "comparison per",
                                           group_label, sep = " ")){

  # check if the data class is correct
  if(!any(class(df) == "ceipr_data")){
    stop("Data is not of class ceipr_data, not valid ceipr data!")
  }

  pollution_totals <- dplyr::group_by(df, .dots = group, year) %>%
    dplyr::summarise(total = sum(emission))
  ggplot(pollution_totals) +
    geom_bar(
      mapping = aes_string(x = "year", y = "total", fill = group),
      stat = "identity",
      position = "dodge"
    ) +
    labs(
      title = title,
      x = "Year",
      y = "Emissions (ton)",
      color = group_label
    )
  }
